version: "3"

services:
  # api:
  #   container_name: api-container
  #   image: "node:16"
  #   working_dir: /app
  #   command: bash -c "npm install && npm run start"
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #     - "9229:9229"
  #   volumes:
  #     - /app/node_modules/
  #     - .:/app
  #   depends_on:
  #     # - mysql
  #     - redis


  mysql:
    container_name: mysql-container
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: munch-root
      MYSQL_DATABASE: munch
    ports:
      - "3306:3306"
    expose:
      - "3306"

  # redis:
  #   image: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   expose:
  #     - "6379"