version: "3.7"

services:
  api:
    image: ghcr.io/munch-ydays/munch-api:v0.2
    working_dir: /app
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.production
    depends_on:
      - mysql

  mysql:
    container_name: mysql-container
    image: mysql
    restart: always
    env_file:
      - .env.production
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    expose:
      - "3306"

  munch-front:
    container_name: munch-front-container
    image: ghcr.io/munch-ydays/munch-front:latest
    working_dir: /app
    restart: always
    ports:
      - 80:80





    